config/routes.rb
SmartGroups::Application.routes.draw do
  root :to => 'welcome#index'

  get '/students_grades' => 'teachers#students_grades'
  resources :metrics
  resources :user_sessions

  get "/parser", to: 'parser#index'
  post "/parser", to: 'parser#import'
  get "users/:user_id/courses/:course_id/metrics/new" => "metrics#main", :as => :main
  post "/metrics", to: 'metrics#create'
  get '/metrics/students/:student_id', to: 'metrics#student_profile', :as => :student_profile

  resources :users do
    resources :students
  end

  post '/courses/:course_id/groups/total_students_per_groups' => "groups#total_students_per_groups"
  post '/courses/:course_id/groups/total_num_of_groups' => "groups#total_num_of_groups"
  post '/courses/:course_id/groups/:id/update_through_ajax' => 'groups#update_through_ajax'

  resources :courses do
    resources :groups

  end

  resources :users do
    resources :courses, only: [:index, :new, :create, :update] , controller: "user_courses"
   end

  post '/login' => 'user_sessions#login'
  get '/logout' => 'user_sessions#logout'
  get "/parser", to: 'parser#index'
  post "/parser", to: 'parser#import'
  get "/users/:user_id/user_courses/:id/edit" => "user_courses#edit", :as => :edit
  put "/users/:user_id/user_courses/:id/edit" => "user_courses#update", :as => :update
end

app/controllers/user_courses_controller.rb
class UserCoursesController < ApplicationController

def index
    if authenticated?
      @courses = User.find(current_user.id).courses
      render :index
    else
      @login_error = "Please login."
      redirect_to root_path
    end

  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create(name: params[:course_title], user_id: current_user.id)

    redirect_to new_user_student_path({user_id: current_user.id, course_id: @course.id})
  end

  def edit
    @course = Course.find(params[:id])
    @all_students = @course.all_students
    @completed_assignments = @course.all_completed_assignments_for_course
  end

  def update
    @sa = StudentAssignment.find(params[:student_assignment][:id])
    @course_id = Assignment.find(@sa.assignment_id).course_id
    @sa.update_attribute(:grade, params[:student_assignment][:grade])
    redirect_to ("/users/#{params[:user_id]}/user_courses/#{params[:id]}/edit")
  end

end

app/views/user_courses/edit.html.erb
<h3>Update Students Info</h3>




<table id="student_info_update_table">
  <tr>
    <th>Name:</th>
    <th>Assignment<br>Name:</th>
    <th>Start<br>Date:</th>
    <th>Due<br>Date:</th>
    <th>Assignment<br>Grade:</th>
    <th>Grade:</th>
  </tr>
  <% @completed_assignments.each do |student_assignment| %>

  <tr><td colspan="6"><hr></td></tr>

  <tr>
    <td>
      <%= student_assignment.student.first_name %> <%= student_assignment.student.last_name %>
    </td>
    <td>
      <%= student_assignment.assignment.assignment_name %>
    </td>
    <td>
      <%= student_assignment.assignment.start_date %>
    </td>
    <td>
      <%= student_assignment.assignment.due_date %>
    </td>
    <td>
      <%= student_assignment.grade %>
    </td>
    <td>
      <%= form_for :student_assignment, :method => 'put' do |f| %>
        <%= f.text_field :grade, {value: student_assignment.grade}%>
        <%= f.hidden_field :id, {value: student_assignment.id} %>
        <%= f.submit "Save Assignment", :confirm => "Are you sure?", class: "small button success", style: "width:150px;float:right;"%>
      <% end %>
      <%= link_to "Delete Assignment",
                  "/users/#{params[:user_id]}/students/#{student_assignment.id}",
                  :method => :delete,
                  :confirm => "Are you sure?",
                  class: "small button alert",  style: "width:150px;float:right;"%>
    </td>

    </tr>
  <% end %>
</table>

app/views/user_courses/index.html.erb
<h3>Welcome to SmartGroup!</h3>


<h4>Add A Course</h4>

<table>
  <tr>
    <td><%= link_to("Add a course with CSV file", parser_path, class: "small button success") %></td>
    <td><%= link_to("Add a course manually", new_user_course_path, class: "small button success") %></td>
  </tr>
</table>

<br><br><br>

<h4>Current Courses</h4>

<table>
  <% @courses.reverse.each do |course| %>
    <tr>
      <td id="display_course_options"><div style="width:200px;"><%= course.name %></div></td>
      <td id="display_course_options"><%= link_to("Group Generator", new_course_group_path(course), class: "small button", id: "course_list_buttons") %></td>
      <td id="display_course_options"><%= link_to("Metics / Graphs", main_path(current_user.id, course.id), class: "small button", id: "course_list_buttons") %></td>
      <td id="display_course_options"><%= link_to("Edit Course", edit_path(current_user.id, course.id), class: "small button", id: "course_list_buttons") %></td>
      <td id="display_course_options"><%= link_to("Delete Course", edit_path(current_user.id, course.id), class: "small button alert", id: "course_list_buttons") %></td>
    </tr>
  <% end %>
</table>

app/views/user_courses/new.html.erb
<h3>Create course title</h3>

<table id="create_course_title_table">
  <%= form_for 'users[courses]', url: {action: "create"} do |f| %>
  <tr>
    <td><%= label_tag("course_title", "Course Title: ")%></td>
  </tr>
  <tr>
    <td><%= text_field_tag("course_title", nil, required: true) %></td>
  </tr>
  <tr>
    <td><%= f.submit "Create New Course", class: "small button success"%></td>
</tr>
  <tr></tr>
<% end %>
</table>