config/routes.rb
SmartGroups::Application.routes.draw do
  root :to => 'welcome#index'

  get '/students_grades' => 'teachers#students_grades'
  resources :metrics
  resources :user_sessions

  get "/parser", to: 'parser#index'
  post "/parser", to: 'parser#import'
  get "users/:user_id/courses/:course_id/metrics/new" => "metrics#main", :as => :main
  post "/metrics", to: 'metrics#create'
  get '/metrics/students/:student_id', to: 'metrics#student_profile', :as => :student_profile

  resources :users do
    resources :students
  end

  post '/courses/:course_id/groups/total_students_per_groups' => "groups#total_students_per_groups"
  post '/courses/:course_id/groups/total_num_of_groups' => "groups#total_num_of_groups"
  post '/courses/:course_id/groups/:id/update_through_ajax' => 'groups#update_through_ajax'

  resources :courses do
    resources :groups

  end

  resources :users do
    resources :courses, only: [:index, :new, :create, :update] , controller: "user_courses"
   end

  post '/login' => 'user_sessions#login'
  get '/logout' => 'user_sessions#logout'
  get "/parser", to: 'parser#index'
  post "/parser", to: 'parser#import'
  get "/users/:user_id/user_courses/:id/edit" => "user_courses#edit", :as => :edit
  put "/users/:user_id/user_courses/:id/edit" => "user_courses#update", :as => :update
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :average, :first_name, :last_name, :group_rating
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :student_assignments
  has_many :assignments, through: :student_assignments



  def get_grades
    self.student_assignments.map {|submitted_assignment| submitted_assignment.grade}
  end

  def name
    "#{self.first_name}" + " #{self.last_name}"
  end

  def average_grade_by_student_assignment(student_assignment)
    grades = []
    studentassignment = StudentAssignment.find(student_assignment.id)
    self.student_assignment
  end

  def completed_assignments_for(course)
    self.student_assignments.where(course_id: course.id)
  end

  def average_grade
    grades = self.get_grades
    average = grades.inject{ |sum, grade| sum + grade }.to_f / grades.length
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @course = Course.find(params[:course_id].to_i)
  end

  def create
    course = Course.find(params[:users][:students][:course])

    # variable naming... please don't use single char vars
    s = Student.create(first_name: params[:users][:students][:first_name], last_name: params[:users][:students][:last_name])
    a = Assignment.create(assignment_name: params[:users][:students][:assignment_name], start_date: params[:users][:students][:start_date], due_date: params[:users][:students][:due_date], course_id: course.id)

    StudentAssignment.create(student_id: s.id, assignment_id: a.id, grade: params[:users][:students][:grade].to_i)
    Enrollment.create(student_id: s.id, course_id: course.id)

    redirect_to new_user_student_path({user_id: params[:user_id], course_id: course.id})
  end

  def destroy
    # variable naming... sa... I get what you mean, but please use better names
    sa = StudentAssignment.find(params[:id])
    course_id = Assignment.find(sa.assignment_id).course_id
    sa.destroy
    redirect_to ("/users/#{params[:user_id]}/user_courses/#{course_id}/edit")
  end

end

app/views/students/edit.html.erb
<!-- what is this? -->
I made it to the student update page

app/views/students/new.html.erb
<h3>Enter Your Students</h3>

<%= form_for 'users[students]', url: {action: "create"} do |f| %>
  <%= f.hidden_field :course, value: "#{@course.id}" %>

  <fieldset>
    <legend>Student Information</legend>

    <div class="row">
      <div class="large-4 columns">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, required: true %>
      </div>
      <div class="large-4 columns">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, required: true %>
      </div>
      <div class="large-4 columns">
        <%= f.label :assignment_name %>
        <%= f.text_field :assignment_name, required: true %>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="large-4 columns">
        <%= f.label :start_date %>
        <%= f.text_field :start_date, required: true %>
      </div>
      <div class="large-4 columns">
        <%= f.label :due_date %>
        <%= f.text_field :due_date, required: true %>
      </div>
      <div class="large-4 columns">
        <%= f.label :grade %>
        <%= f.text_field :grade, required: true %>
      </div>
    </div>

    <br>

    <div class="row">
      <%= f.submit "Add Student", class: "small button success", style: "float:right;width:150px;margin-right:15px" %>
      <%= link_to("Back to Course list", user_courses_path(params[:user_id]), class: "small button", style: "float:right;width:150px;margin-right:30px") %>
    </div>

  </fieldset>
<% end %>

app/views/students/show.html.erb
<!-- what is this? -->
students show page