config/routes.rb
SmartGroups::Application.routes.draw do
  root :to => 'welcome#index'

  get '/students_grades' => 'teachers#students_grades'
  resources :metrics
  resources :user_sessions

  get "/parser", to: 'parser#index'
  post "/parser", to: 'parser#import'
  get "users/:user_id/courses/:course_id/metrics/new" => "metrics#main", :as => :main
  post "/metrics", to: 'metrics#create'
  get '/metrics/students/:student_id', to: 'metrics#student_profile', :as => :student_profile

  resources :users do
    resources :students
  end

  post '/courses/:course_id/groups/total_students_per_groups' => "groups#total_students_per_groups"
  post '/courses/:course_id/groups/total_num_of_groups' => "groups#total_num_of_groups"
  post '/courses/:course_id/groups/:id/update_through_ajax' => 'groups#update_through_ajax'

  resources :courses do
    resources :groups

  end

  resources :users do
    resources :courses, only: [:index, :new, :create, :update] , controller: "user_courses"
   end

  post '/login' => 'user_sessions#login'
  get '/logout' => 'user_sessions#logout'
  get "/parser", to: 'parser#index'
  post "/parser", to: 'parser#import'
  get "/users/:user_id/user_courses/:id/edit" => "user_courses#edit", :as => :edit
  put "/users/:user_id/user_courses/:id/edit" => "user_courses#update", :as => :update
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController

  def main
    @course = Course.find(params[:course_id])
    session[:course_id] = @course.id
    @chart_types = [{id: 1, type: "Each Student's Assignment Scores by Assignment"}, {id: 2, type: "Individual Student Performance by Assignment Due Date"}, {id: 3, type: "Class Average Assignment Scores by Due Date"}]
  end

  def create
    @selections = params['chart_selections']
    @course = Course.find(session[:course_id])
    @completed_assignments = @course.all_completed_assignments_for_course
    @class_averages = Array.new
    @hash = {}
    @categories = @course.get_assignment_names
    @range_categories = @course.get_assignment_names

    @completed_assignments.each do |student_assignment|
      @student_grades = student_assignment.student.get_grades
      @class_averages << student_assignment.assignment.course_average
      @hash[student_assignment.student.name] = @student_grades
    end

    @class_average = @course.get_mean

    graph_generator = GraphGenerator.new(@hash, @course.id)
    graph_generator.generate!

    @chart = graph_generator.column_graph(@categories, @class_averages)

    @chart_area = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:chart][:defaultSeriesType] = "spline"
      @hash.each do |k,v|
        f.series(:type=> "spline",:name=> "#{k}", :data=> v, visible: false)
      end
      f.options[:chart][:inverted] = false
      f.options[:legend][:layout] = "horizontal"
      f.options[:xAxis][:categories] = @categories
      f.options[:legend][:layout] = "horizontal"
    end

    @chart_range = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:chart][:defaultSeriesType] = "spline"
      f.series(:type=>"spline", :name=> "Class Average", :data=> @class_averages)
      f.options[:chart][:inverted] = false
      f.options[:legend][:layout] = "horizontal"
      f.options[:xAxis][:categories] = @range_categories.uniq!
    end

    if @selections == nil
      redirect_to main_path(session[:user_id],session[:course_id])
    else
      render :show
    end
  end


  def student_profile
   @student = Student.find(params[:student_id])
   @course = Course.find(session[:course_id])
   @student_name = @student.name
   @averages = Array.new
   @student_grades = []
   @axis_labels = Array.new
   @course_average_grades = Array.new
   @course_average = @course.get_student_grades
   @hash_student = Hash.new

   @course.completed_assignments_for(@student).each do |student_assignment|
    @axis_labels << student_assignment.assignment.assignment_name
    @student_grades << student_assignment.grade
    @averages << Float(@student_grades.inject(:+))/@student_grades.length
    @course_average_grades << student_assignment.assignment.course_average
  end
  @chart_student = LazyHighCharts::HighChart.new('graph') do |f|
    f.title({ :text=> @course.name})
    f.series(:type=> "spline",:name=> @student_name, :data=> @averages)
    f.series(:type=> "spline",:name=> "#{@course.name}", :data=> @course_average_grades)

    f.options[:xAxis][:categories] = @axis_labels
    f.options[:legend][:layout] = "horizontal"
    f.labels(:items=>[:html=>"#{@student_name}", :style=>{:left=>"40px", :top=>"8px", :color=>"black"} ])
  end
  render :student_profile
end

end

app/helpers/metrics_helper.rb
module MetricsHelper

  def get_average(array)
    array.inject{ |sum, element| sum + element }.to_f / array.length
  end

  def selected_chart_type?(selections,at_index)
    type1 = "Each Student's Assignment Scores by Assignment"
    type2 = "Individual Student Performance by Assignment Due Date"
    type3 = "Class Average Assignment Scores by Due Date"

    types = [type1, type2, type3]

    if selections != nil
      if selections.include?(types[at_index])
        true
      else
        false
      end
    else
      false
    end
  end

end

app/views/metrics/main.html.erb
<h2>Metrics/Graphs</h2>
<h4 class="subheader"><%= Course.find(params[:course_id]).name %></h4>
<hr>

<br><br><br>
<h3 class="subheader"><%= "View Multiple Students" %></h3>

<%= form_tag ("/metrics"), method:"POST" do %>
  <table>
  <tr>
    <th>Select Chart</th>
    <th style="text-align:left;">Chart Description</th>
  </tr>

     <% @chart_types.each do |chart_type| %>
      <tr>
        <td style="text-align:center;"><%= check_box_tag 'chart_selections[]', chart_type[:type] -%></td>
        <td><%=chart_type[:type]%></td>
      </tr>

      <% end %>
      <tr>
        <td style="text-align:center;"><%= submit_tag "Submit", class: "small button success" %></td>
        <td</td>
      </tr>
  </table>
<% end %>




<br><br><br>

<h3 class="subheader"><%= "View An Individual Student" %></h3>
<table>
  <%  @course.students.each do |student| %>
    <tr>
      <td><%= link_to(student.name, student_profile_path(student.id)) -%></td>
    </tr>
  <% end %>
</table>

app/views/metrics/show.html.erb
<h2>Charts for <%= Course.find(session[:course_id]).name %></h2>

<% if selected_chart_type?(@selections, 0) %>
<h3>Compare Student Performance by Assignment, to Peers and Class Mean </h3>

<%= high_chart("chart_div", @chart) %>

<% end %>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>




<% if selected_chart_type?(@selections, 1) %>

<h3>Compare Student Assignment Scores vs Class Mean Over Time </h3>



<%= high_chart("area_div", @chart_area) %>


<% end %>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<% if selected_chart_type?(@selections, 2) %>

<h3>Class Mean Score Trend Over Time </h3>



<%= high_chart("chart_range_div", @chart_range) %>

<% end %>

app/views/metrics/student_profile.html.erb
<h2><%= @student.name %></h2>

<h3><%= "Chart for" + " #{@student.name}" + " #{@course.name}" %></h3>

<%= high_chart("student_chart_div", @chart_student) %>